FAQ Updates
IBM/ibmz-accelerated-for-tensorflow pull request #4
Opened 2024-01-20 15:31 UTC by willjones1989

- Updated Training Workloads section to advise setting `NNPA_DEVICES=0`.
- Added example usages of the environment variables that can be used for verification and debugging.

2024-01-22 16:09 UTC, pksubbarao approved these changes

2024-01-23 14:25 UTC, willjones1989 commented on README.md
> +As discuessed in [Environment Variables for Logging](#env-variables), there are
spell check

2024-01-25 14:02 UTC, kyleg907 requested changes
Requesting lint'ers to be run as discussed at our review.

2024-01-30 14:59 UTC, pksubbarao approved these changes

2024-01-31 18:35 UTC, Vezio approved these changes
LGTM

2024-02-06 21:49 UTC, kyleg907 approved these changes

2024-02-06 22:00 UTC, merged